global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'wal-g-exporter'
    static_configs:
      - targets: ['wal-g-exporter:9351']
    scrape_interval: 60s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # Add alerting rules here if needed