name: Regression Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        postgres_version: [12, 13, 14, 15, 16, 17, 18]

    name: "Test on PostgreSQL ${{ matrix.postgres_version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start PostgreSQL
        run: |
          docker run --name postgres -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 -d postgres:${{ matrix.postgres_version }}
          sleep 10

      - name: Prepare DB
        run: |
          docker exec postgres psql -U postgres -c 'create database test'
          docker exec postgres psql -U postgres test -c 'create extension pg_stat_statements'
          docker exec postgres psql -U postgres test -c 'create extension pgstattuple'
          docker exec postgres psql -U postgres test -c "create table align1 as select 1::int4, 2::int8, 3::int4 as more from generate_series(1, 100000) _(i);"
          docker exec postgres psql -U postgres test -c "create table align2 as select 1::int4, 3::int4 as more, 2::int8 from generate_series(1, 100000) _(i);"

      - name: Tests
        run: |
          echo "\set postgres_dba_wide true" > ~/.psqlrc
          echo "\set postgres_dba_interactive_mode false" >> ~/.psqlrc
          for f in ./sql/*; do docker exec -i postgres psql -U postgres test -f warmup.psql -f "$f" >/dev/null; done
          echo "\set postgres_dba_wide false" > ~/.psqlrc
          echo "\set postgres_dba_interactive_mode false" >> ~/.psqlrc
          for f in ./sql/*; do docker exec -i postgres psql -U postgres test -f warmup.psql -f "$f" >/dev/null; done
          diff -b test/regression/0_node.out <(docker exec -i postgres psql -U postgres test -f warmup.psql -f ./sql/0_node.sql | grep Role)
          diff -b test/regression/p1_alignment_padding.out <(docker exec -i postgres psql -U postgres test -f warmup.psql -f ./sql/p1_alignment_padding.sql | grep align)
          diff -b test/regression/a1_activity.out <(docker exec -i postgres psql -U postgres test -f warmup.psql -f ./sql/a1_activity.sql | grep User)
